language: python

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ppa:ansible/ansible
    packages:
    - ansible

addons:
  homebrew:
    packages:
      - ansible

before_install:
  - cp inventory.ci inventory
  - cp extra_vars.yml.sample extra_vars.yml

script:
  - ansible-playbook -i inventory --extra-vars @extra_vars.yml dev-vm.yaml
