language: generic

os:
  - linux
  - osx
dist: bionic

addons:
  apt:
    sources:
      - sourceline: "ppa:ansible/ansible"
    packages:
      - python
      - python-pip
      - ansible
  homebrew:
    packages:
      - ansible

env:
  - PATH=$PATH:$HOME/.gem/ruby/2.4.0/bin

before_install:
  - cp inventory.ci inventory
  - cp extra_vars.yml.sample extra_vars.yml
  - sed -Ei.bk "s/^(docker.) true/\1 false/" extra_vars.yml
  - sed -Ei.bk "s/^(ruby.) true/\1 false/" extra_vars.yml
  - echo "[defaults]" > ansible.cfg
  - echo "callback_whitelist = profile_tasks" >> ansible.cfg
  - ansible --version
  # lots of cask installs seems to fail on CI.
  - "echo 'homebrew_cask_package_list: \n' >> extra_vars.yml"
  - "echo '  - visual-studio-code\n' >> extra_vars.yml"
  - "echo 'homebrew_package_list: \n' >> extra_vars.yml"
  - "echo '  - wget\n' >> extra_vars.yml"
  - "echo '  - tmux\n' >> extra_vars.yml"
  - env

install:
  # try to upgrade ansible
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew upgrade ansible; fi

script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then ansible-playbook -i inventory --extra-vars @extra_vars.yml -vvv dev-vm.yaml; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; travis_wait 30 ansible-playbook -i inventory --extra-vars @extra_vars.yml -vvv dev-vm.yaml; fi
