language: python

sudo: required

services:
  - docker

before_install:
  - cp inventory.ci inventory
  - cp extra_vars.yml.sample extra_vars.yml
  - docker build -t huxoll-dev-vm .

script:
  - docker run -it huxoll-dev-vm
