version: '3'
services:
  ${platform}:
    build:
      context: ${work_dir}
      dockerfile: Dockerfile.dev
    command: /bin/bash
    ports:
    - "5000:5000"
    volumes:
    - ${work_dir}:/code
    - logvolume01:/var/log
    stdin_open: true
    tty: true
volumes:
  logvolume01: {}
