# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/gardnerj/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# Maybe: per-directory-history
plugins=(git battery brew osx shrink-path)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

export DOCKER_ID_USER="huxoll"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH=$HOME/bin:$PATH

# Go Path
export GOPATH=$HOME/go
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/go_appengine

# Ant
ANT_HOME=/usr/local/apache-ant-1.8.4
ANT_OPTS=-Xmx256m

# Add jenv for selection of homebrew java version.
export PATH="$HOME/.jenv/bin:$PATH"
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/gardnerj/.sdkman"
[[ -s "/Users/gardnerj/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/gardnerj/.sdkman/bin/sdkman-init.sh"

export DEFAULT_USER="gardnerj"

# AWS
#export AWS_CREDENTIAL_FILE=~/Projects/Transcend/aws/.awscreds
#export AWS_CLOUDWATCH_HOME=~/Projects/Transcend/aws/CloudWatch-1.0.13.4
#export PATH=$PATH:$AWS_CLOUDWATCH_HOME/bin

# Kubernetes
#export KUBECONFIG=~/.kube/cava-config.yaml

# Google Compute
#export PATH=$PATH:~/bin/gcutil-1.5.0

jhg_prompt_dir() {
  prompt_segment blue $CURRENT_FG "$(shrink_path -f -2)"
}

## Main prompt
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_virtualenv
  prompt_aws
  prompt_context
  jhg_prompt_dir
  prompt_git
  prompt_bzr
  prompt_hg
  prompt_end
}

# Add z utility
. ~/bin/z.sh
#setopt prompt_subst
#PS1='%{%f%b%k%} $(build_prompt) $(shrink_path -f)>'

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
#[[ -s "/Users/jgardner/.gvm/bin/gvm-init.sh" ]] && source "/Users/jgardner/.gvm/bin/gvm-init.sh"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# Apps and Containers
# defeat muscle memory
alias e='code --goto'
alias more='less'
alias mroe='less'
alias ls='ls -F'
alias opne='open'

# Tools and utilities
alias t='history'
# Development shortcuts
#alias mvno="mvn -o"
#alias mvnq="mvn -o -Dmaven.test.skip=true"

# Current Project
alias gov="cd ~/Projects/VMware"
# Cloud Selection
alias eu3=". ~/.aws/eu3-jgardner/eucarc"
# VMware
alias vmrun="/Applications/VMWare\ Fusion.app/Contents/Library/vmrun"
# Kubernetes
alias k="kubectl"
alias kstaging="export KUBECONFIG=/Users/gardnerj/.kube/scdc1-staging-vmw-piv-labs.yaml"
function git_current_branch() {
  git symbolic-ref HEAD 2> /dev/null | sed -e 's/refs\/heads\///'
}

# Git
alias gpthis='git push origin HEAD:$(git_current_branch)'
alias grb='git rebase -p'
alias gm='git merge --no-ff'
alias glog='git log --oneline --decorate'
alias gup='git up'

# Personal Aliases
alias gog="cd ~/Google\ Drive"
alias gop="cd ~/Projects/Personal"

# Useful nav
alias gomaps="~/Google\ Drive/Games/Maps"
alias godnd="~/Google\ Drive/Games/DND"
alias gotokens="~/Google\ Drive/Games/Tokens"